import React, { createContext, useContext, useState } from "react";

const translations = {
  en: {
    nav: {
      home: "Home", about: "About", services: "Services", cars: "Cars",
      blog: "Blog", teams: "Teams", contact: "Contact",
      login: "Login", register: "Sign Up", profile: "My Account",
      bookingHistory: "Booking History", cart: "Cart", logout: "Logout",
      admin: "Admin", needHelp: "Need help?", promotions: "Promotions",
    },
    auth: {
      loginTitle: "Login", loginSub: "Welcome back!",
      email: "Email", password: "Password", forgotPwd: "Forgot password?",
      loggingIn: "Logging in...", loginBtn: "Login",
      noAccount: "Don't have an account?", registerLink: "Sign up",
      registerTitle: "Sign Up", registerSub: "Create an account to rent easily",
      fullName: "Full Name", phone: "Phone Number",
      confirmPwd: "Confirm Password", registering: "Signing up...", registerBtn: "Sign Up",
      hasAccount: "Already have an account?", loginLink: "Login",
      pwdMismatch: "Passwords do not match", pwdTooShort: "Password must be at least 6 characters",
      registerSuccess: "Registration successful!",
    },
    cars: {
      bannerSub: "- RENT NOW", bannerTitle1: "Select", bannerTitle2: "Luxury Car",
      searchPlaceholder: "Search by brand, model...", categories: "Categories", all: "All",
      noResults: "No matching cars found",
      viewDetails: "View Details", perDay: "/day",
      transmission: "Transmission", fuel: "Fuel", mileage: "Mileage", seats: "Seats",
      noImage: "No image available",
      statusLabel: { available: "Available", rented: "Rented", maintenance: "Maintenance" },
      color: "Color",
      filters: "Filters",
      priceRange: "Price Range",
      minPrice: "Min",
      maxPrice: "Max",
      sortBy: "Sort by",
      sortNewest: "Newest",
      sortPriceAsc: "Price: Low to High",
      sortPriceDesc: "Price: High to Low",
      sortYearDesc: "Year: Newest first",
      transmissionAuto: "Automatic",
      transmissionManual: "Manual",
      transmissionCVT: "CVT",
      fuelPetrol: "Petrol",
      fuelDiesel: "Diesel",
      fuelElectric: "Electric",
      fuelHybrid: "Hybrid",
      anyTransmission: "Any transmission",
      anyFuel: "Any fuel",
      resetFilters: "Reset Filters",
      activeFilters: "Active Filters",
      foundResults: "found",
      clear: "Clear",
    },
    carDetails: {
      category: "LUXURY CARS",
      generalInfo: "General Information",
      generalDesc: "Enjoy a premium car rental experience with top-notch services and flexible conditions.",
      support: "24/7 Roadside Assistance",
      freeCancellation: "Free Cancellation & Return",
      payOnArrival: "Pay At Arrival",
      rentalConditions: "Rental Conditions",
      conditions: [
        { title: "Contract & Documents", description: "You must have ID, a driver's license, and a deposit when signing the rental contract." },
        { title: "Payment", description: "The total rental fee is collected at the time of pickup. Additional costs are calculated based on actual distance." },
        { title: "Delivery", description: "Free delivery within the same area. Delivery to another city will incur a travel fee." },
        { title: "Traffic Violations", description: "The renter is responsible for all traffic violations. Please notify us if fined." },
      ],
      available: "Available", unavailable: "Unavailable",
      rented: "Rented", maintenance: "Maintenance",
      seatsLabel: "Seats", transmissionLabel: "Transmission", fuelLabel: "Fuel",
      mileageLabel: "Mileage", acLabel: "Air Conditioning", yes: "Yes",
      colorLabel: "Color", descriptionLabel: "Description",
      rentNow: "Rent Now", perDay: "/day", seatsUnit: "seats",
      selectDates: "Select Rental Dates",
      pickupDate: "Pickup Date *", returnDate: "Return Date *",
      total: "Total:", days: "days",
      addToCart: "Add to Cart",
      loginRequired: "Please login to book a car",
      selectDatesError: "Please select pickup and return dates",
      returnAfterPickup: "Return date must be after pickup date",
      addedToCart: "Added to cart!",
      carNotFound: "Car not found",
    },
    cart: {
      title: "Confirm Booking",
      empty: "Your cart is empty",
      browseCars: "Browse Cars",
      pickupDate: "Pickup Date:", returnDate: "Return Date:",
      numDays: "Number of Days:", days: "days",
      voucherPlaceholder: "Enter discount code",
      applyVoucher: "Apply",
      subtotal: "Subtotal", discount: "Discount", total: "Total",
      perDay: "/day", confirmBtn: "Confirm Booking",
      processing: "Processing...",
      voucherSuccess: "Voucher applied! Saved",
      invalidVoucher: "Invalid code", bookingError: "Cannot create booking",
      seats: "seats",
      tripDetails: "Trip Details",
      pickupLocation: "Pickup Location",
      pickupLocationPlaceholder: "e.g. District 1, HCM City",
      dropoffLocation: "Drop-off Location",
      dropoffLocationPlaceholder: "Same as pickup or different",
      notes: "Notes for the staff",
      notesPlaceholder: "Any special requests? (optional)",
    },
    bookingHistory: {
      title: "Booking History",
      empty: "You have no bookings yet",
      status: { pending: "Pending", confirmed: "Confirmed", active: "Active", completed: "Completed", cancelled: "Cancelled" },
      payment: {
        statusLabel: "Payment",
        methodLabel: "Method",
        unpaid: "Unpaid", paid: "Paid", refunded: "Refunded",
        cash: "Cash", card: "Card", mock: "Online",
      },
      bookingId: "Booking ID",
      createdAt: "Booked on",
      discount: "Discount",
      notes: "Notes",
      pickup: "Pickup",
      return: "Return",
      duration: "Duration",
      payNow: "Pay Now",
      cancelBtn: "Cancel Booking",
      cancelConfirm: "Are you sure you want to cancel this booking?",
      cancelSuccess: "Booking cancelled",
      cancelError: "Cannot cancel",
      loadError: "Cannot load booking history",
    },
    profile: {
      title: "My Account",
      tabInfo: "Personal Info", tabPwd: "Change Password",
      fullName: "Full Name", phone: "Phone Number", address: "Address",
      city: "City", state: "Province/City", zipCode: "Zip Code",
      avatar: "Avatar URL", avatarPlaceholder: "https://example.com/photo.jpg",
      saveBtn: "Save Changes", saving: "Saving...", saveSuccess: "Updated successfully!",
      currentPwd: "Current Password", newPwd: "New Password", confirmPwd: "Confirm New Password",
      changePwdBtn: "Change Password", changePwdSuccess: "Password changed!",
      pwdMismatch: "Passwords do not match",
    },
    payment: {
      title: "Payment",
      orderSummary: "Order Summary",
      car: "Car", pickupDate: "Pickup Date", returnDate: "Return Date", total: "Total",
      paymentMethod: "Payment Method",
      creditCard: "Credit Card (Simulated)", card: "Real Credit Card", cash: "Cash on Pickup",
      payBtn: "Pay", paying: "Processing...",
      successTitle: "Payment Successful!",
      successDesc: "Your booking has been confirmed.",
      viewHistory: "View Booking History",
      loadError: "Cannot load booking info",
      payError: "Payment failed",
      paySuccess: "Payment successful!",
    },
    chatbot: {
      title: "CarShops Assistant",
      subtitle: "Support 24/7",
      placeholder: "Type a message...",
      greeting: "Hello! I'm your car rental assistant. How can I help you?",
      errorReply: "Sorry, I'm unable to respond right now. Please try again later.",
    },
    promotions: {
      title: "Active Promotions",
      subtitle: "Apply these codes at checkout to save more on your rental",
      empty: "No active promotions at the moment",
      copyCode: "Copy Code",
      copied: "Copied!",
      percentOff: "OFF",
      flatOff: "OFF",
      minOrder: "Min order",
      maxDiscount: "Max discount",
      validUntil: "Valid until",
      validFrom: "Valid from",
      usesLeft: "uses left",
      noLimit: "No limit",
      apply: "Apply this code in the cart",
      loadError: "Cannot load promotions",
    },
    common: {
      loading: "Loading...",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      close: "Close",
      confirm: "Confirm",
    },
    index: {
      heroPremium: "Premium",
      heroTitle: "CAR RENTAL",
      heroSubtitle: "BOOK ONLINE NOW AT THE BEST PRICE",
      heroDesc: "Experience premium car rental with comfort, style and affordable prices — perfect for long trips, business travel, or luxury weekend getaways.",
      heroViewNow: "View Now",
      heroRegister: "Register Here",
      selectCarType: "Select Return Car Type",
      pickLocation: "Pickup Location",
      dropLocation: "Drop Location",
      pickDate: "Departure Date",
      returnDate: "Return Date",
      aboutSub: "Car Rental",
      aboutTitle1: "We offer more than",
      aboutTitle2: "a regular car rental",
      aboutDesc: "Our system aims to provide a flexible booking experience with the ability to cancel or modify before your pickup time.",
      aboutFeature1: "Sports and luxury cars",
      aboutFeature2: "Economy cars",
      aboutReadMore: "Read More",
      bookBannerSub: "Rent Now",
      bookBannerTitle: "Auto Booking",
      luxurySub: "Choose Your Car",
      luxuryTitle1: "Available",
      luxuryTitle2: "Cars",
      carDescBtn: "Details",
      carTypeSub: "Choose Your Car",
      carTypeTitle1: "Available",
      carTypeTitle2: "Car Types",
      carTypeConvertible: "Convertible",
      carTypeSport: "Sports Car",
      carTypeLuxury: "Luxury Car",
      carTypeSmall: "Small Car",
      serviceSub: "What We Do",
      serviceTitle: "To Serve Our Customers",
      service1Title: "Daily Car Rental",
      service1Desc: "Rent a car by the day, choose your vehicle and specific rental time to suit short-term travel needs.",
      service2Title: "Monthly Car Rental",
      service2Desc: "Car rental for over 1 month falls under our long-term service, available for both individual and corporate customers.",
      service3Title: "Wedding Car Rental",
      service3Desc: "Wedding cars are an important element to make your big day more perfect. A vital vehicle on your wedding day (We do not offer wedding car decoration).",
      testSub: "Reviews (Demo)",
      testTitle1: "What Our Customers Say",
      testTitle2: "(Sample Data)",
      testRole: "Customer",
      testReview1: "Absolutely wonderful",
      testReview2: "Will definitely come back!",
      testReview3: "First time I've seen a garage that rents luxury cars this affordably!!!",
      testReview4: "I am a foreigner residing in Vietnam. I find the service here to be excellent.",
      testReview5: "Clean car interior, they even called 25 minutes before arrival.",
      blogSub: "Articles About Us",
      blogTitle1: "Essential",
      blogTitle2: "News",
      blogCategory: "Cars",
      blogPost1: "Required documents for car rental",
      blogPost2: "Cost of renting sports cars and other vehicles.",
      blogPost3: "Car rental: How to check traffic fines while driving?",
      blogPost4: "How to rent a car at the airport terminal?",
    },
    about: {
      bannerSub: "- Information",
      bannerTitle1: "About",
      bannerTitle2: "Us",
      heading1: "We offer more than",
      heading2: "a regular car rental",
      desc: "Most rental bookings allow free cancellation or modification.",
      carType: "Car Type",
      suv: "SUV",
      luxury: "Luxury",
      sedan: "Sedan",
      pickLocation: "Pickup Location",
      dropLocation: "Drop Location",
      pickDate: "Departure Date",
      returnDate: "Return Date",
      bookBtn: "Book Now",
    },
    services: {
      bannerSub: "- What We Do",
      bannerTitle1: "To",
      bannerTitle2: "Serve You",
      servicesSub: "What We Do",
      servicesTitle: "To Serve Our Customers",
      card1Title: "Corporate Car Rental",
      card1Desc: "Corporate car rental supports organizations and companies in renting vehicles for long-term or contract use, optimizing costs and management efficiency.",
      card2Title: "Chauffeur Service",
      card2Desc: "Chauffeured car rental lets customers choose a vehicle with a driver, ideal for safe, convenient travel without self-driving.",
      card3Title: "Airport Transfer",
      card3Desc: "Airport transfer allows customers to book a car between the airport and desired locations, ensuring punctuality, convenience, and safety.",
      card4Title: "Multi-Vehicle Booking",
      card4Desc: "Allows individuals or businesses to book multiple vehicles at once, meeting the needs of events, tours, or large-scale transportation.",
      card5Title: "VIP Service (Coming Soon!)",
      card5Desc: "VIP service provides premium features with special offers, dedicated support, and superior experiences for high-demand users.",
      card6Title: "Business Car Rental",
      card6Desc: "Business car rental supports organizations and companies in renting vehicles for long-term or contract needs, optimizing cost and management efficiency.",
      dailyTitle: "Daily Rental",
      dailyDesc: "Rent a car by the day, choose your vehicle and rental time to suit short-term travel needs.",
      monthlyTitle: "Monthly Rental",
      monthlyDesc: "Car rental for over 1 month is our long-term service, available for both individual and business customers.",
      weddingTitle: "Wedding Car",
      weddingDesc: "Wedding cars are an important element to make your day more perfect (We do not offer wedding car decoration).",
    },
    contact: {
      bannerSub: "Contact Now",
      bannerTitle1: "With",
      bannerTitle2: "Us",
      addressLabel: "Address",
      hoursLabel: "Working Hours",
      hoursValue: "Mon - Sun: 8:00 - 19:00",
      phoneLabel: "Phone",
      formTitle: "Send Us a Message",
      namePlaceholder: "Full Name*",
      phonePlaceholder: "Phone Number*",
      subjectPlaceholder: "Subject*",
      messagePlaceholder: "Message*",
      sendBtn: "Send Message",
    },
    teams: {
      bannerSub: "CONSULTANT",
      bannerTitle: "Olivia Brown (Sample Data)",
      greeting: "Hello, I am Olivia Brown – a consultant at the premium car rental system.",
      memberDesc: "Helping customers choose the right car, advising on services, and ensuring a convenient, fast rental experience.",
      license: "Class B Driver License",
      education: "University Graduate",
      communication: "Strong Communication Skills",
      tab1: "Biography",
      tab2: "Education",
      tab3: "Achievements",
      bio: "Car rental consultant with experience in customer care and vehicle selection support. Capable of fast, accurate advice to provide the best experience for customers.",
      edu: "Graduated in Information Technology / Business Administration. Trained in communication skills, service management, and customer support systems in a digital environment.",
      achievement: "Received employee of the year award, contributing greatly to improving service quality and enhancing user experience on the online car rental platform.",
      teamSub: "- Professional Team",
      teamTitle1: "Our",
      teamTitle2: "Expert Team",
      dept: "Sales Department",
    },
    footer: {
      quickRentSub: "Quick Rent",
      quickRentTitle: "Without Pre-booking?",
      quickRentDesc: "Don't Hesitate — Message Us",
      callLabel: "Call Me At",
      emailLabel: "Email Feedback",
      addressLabel: "Booking Address",
      tagline: "Experience the ease and convenience of renting a car with Carshops.",
      quickLinks: "Quick Links",
      subscribe: "Subscribe",
      subscribeDesc: "Follow us to receive the latest deals.",
      emailPlaceholder: "Your email address",
      copyright: "All rights reserved.",
    },
    admin: {
      sidebar: {
        addCar: "Add New Car",
        manageCars: "Manage Fleet",
        bookings: "Reservations",
        users: "Users",
        categories: "Categories",
        vouchers: "Vouchers",
        financial: "Financial",
        reports: "Reports",
        chat: "Chat Sessions",
        logout: "Logout"
      },
      common: {
        welcome: "Welcome back",
        dashboard: "Admin Dashboard",
        search: "Search directory...",
        actions: "Actions",
        status: "Status",
        save: "Save Changes",
        discard: "Discard",
        loading: "Loading system data...",
        noResults: "No results found",
        error: "Error",
        saveSuccess: "Saved successfully",
        loadingError: "Failed to load data",
        confirmDelete: "This action cannot be undone. Continue?",
        add: "Add", edit: "Edit", cancel: "Cancel", create: "Create", delete: "Delete",
        active: "Active", inactive: "Suspended"
      },
      pagination: {
        showing: "Showing",
        to: "to",
        of: "of",
        results: "results",
        prev: "Previous",
        next: "Next",
        rowsPerPage: "Rows per page"
      },
      cars: {
        title: "Fleet Inventory",
        stats: {
          total: "Total Fleet", unit: "vehicles",
          available: "Available", rented: "Rented", maintenance: "Maintenance"
        },
        filters: { allStatus: "All Status" },
        table: { identity: "Vehicle Identity", specs: "Specifications", rate: "Daily Rate" },
        modal: {
          title: "Update Vehicle",
          make: "Automaker", model: "Model", year: "Release Year",
          rate: "Daily Rate ($)", trans: "Transmission", fuel: "Fuel Type",
          seats: "Seats", mileage: "Mileage (MPG)", color: "Color",
          category: "Category", description: "Description",
          image: "Vehicle Image", currentImage: "Current image",
          uploadNew: "Upload new image", keepCurrent: "Keep current image",
          deleteConfirm: "Are you sure you want to delete this vehicle?"
        }
      },
      bookings: {
        title: "Booking Operations",
        stats: {
          total: "Total Bookings",
          active: "Active", revenue: "Revenue (paid)", pending: "Pending",
          confirmed: "Confirmed", completed: "Completed", cancelled: "Cancelled"
        },
        filters: { allStatus: "All Status", allPayment: "All Payments" },
        payment: {
          status: "Payment Status",
          method: "Payment Method",
          unpaid: "Unpaid", paid: "Paid", refunded: "Refunded",
          cash: "Cash", card: "Card", mock: "Mock"
        },
        table: { customer: "Customer", car: "Car", duration: "Stay", amount: "Amount" },
        modal: {
          title: "Reservation Details",
          summary: "Order Summary", financials: "Financials",
          days: "Total Days", payment: "Payment Mode",
          bookingId: "Booking ID", createdAt: "Created", notes: "Notes",
          discount: "Discount", subtotal: "Subtotal",
          updateStatus: "Update Status", cancelBooking: "Cancel Booking",
          cancelConfirm: "Are you sure you want to cancel this booking?"
        }
      },
      users: {
        title: "User Directory",
        stats: {
          total: "Total Directory", privilege: "Admins",
          acquisition: "7d New", customers: "Customers"
        },
        filters: { allRoles: "All Roles", admin: "Admins", customer: "Customers" },
        table: { identity: "User Identity", contact: "Contact Details", role: "Access Role", joined: "Registration" },
        roles: { admin: "Admin", customer: "Customer" },
        modal: {
          addTitle: "Create New User",
          editTitle: "Edit User",
          name: "Full Name", email: "Email", password: "Password",
          phone: "Phone", role: "Role", status: "Account Status",
          passwordHint: "Minimum 6 characters",
          deleteConfirm: "Permanently delete this user?",
          activate: "Activate", suspend: "Suspend",
          selfTag: "You",
          selfActionDisabled: "You cannot change your own role or status"
        }
      },
      addCar: {
        title: "List Your",
        titleHighlight: "Vehicle",
        subtitle: "Fill in the details below to add your car to our rental fleet",
        labels: {
          name: "Car Name",
          price: "Daily Price ($)",
          seats: "Seats",
          fuel: "Fuel Type",
          mileage: "Mileage (MPG)",
          category: "Category",
          year: "Year",
          model: "Model",
          transmission: "Transmission",
          color: "Color",
          description: "Description",
          image: "Car Image"
        },
        placeholders: {
          name: "e.g., Toyota Camry",
          price: "45",
          mileage: "28",
          year: "2020",
          model: "e.g., XLE",
          description: "Describe your vehicle...",
          upload: "Click to upload",
          drop: "or drag and drop",
          imageTypes: "PNG, JPG, WEBP up to 10MB"
        },
        success: {
          title: "Congratulations!",
          message: "has been listed successfully"
        },
        submit: "Add Vehicle",
        sections: {
          info: "General Information",
          specs: "Technical Details",
          media: "Media & Features",
          preview: "Live Listing Preview"
        }
      },
      financial: {
        title: "Financial Overview",
        subtitle: "Transaction history and revenue statistics",
        stats: {
          revenue: "Total Revenue",
          revenueSub: "From successful transactions",
          transactions: "Total Transactions",
          transactionsSub: "All status levels",
          growth: "Success Rate",
          growthSub: "transactions",
          pending: "Pending Revenue",
          pendingSub: "Awaiting confirmation",
          refunded: "Refunded",
          refundedSub: "Returned to customers",
          avg: "Avg Transaction",
          avgSub: "Per successful tx"
        },
        filters: { allStatus: "All Statuses", allMethods: "All Methods", from: "From", to: "To", reset: "Reset" },
        methods: { cash: "Cash", card: "Card", mock: "Mock" },
        table: {
          id: "TX ID",
          customer: "Customer",
          method: "Method",
          amount: "Amount",
          status: "Status",
          date: "Date"
        },
        status: {
          success: "Success",
          pending: "Pending",
          failed: "Failed",
          refunded: "Refunded",
          all: "All Statuses"
        },
        modal: {
          title: "Transaction Details",
          gatewayRef: "Gateway Reference",
          description: "Description",
          customer: "Customer",
          bookingId: "Booking ID",
          createdAt: "Created at",
          updatedAt: "Updated at",
          changeStatus: "Change Status",
          refund: "Refund",
          markPaid: "Mark as Paid",
          refundConfirm: "Mark this transaction as refunded? Booking payment status will be set to 'refunded'."
        },
        export: "Export Excel"
      },
      categories: {
        title: "Category Management",
        addBtn: "Add Category",
        stats: { total: "Total Categories", active: "Active", hidden: "Hidden", carsTagged: "Tagged Cars" },
        table: { name: "Name", count: "Vehicles", status: "Status" },
        modal: {
          create: "Create Category", edit: "Edit Category",
          name: "Category Name", icon: "Icon (Emoji/Char)", desc: "Description",
          deleteConfirm: "Hide this category?",
          deleteWithCarsWarning: "This category has {n} vehicle(s) assigned. Hiding it won't remove them but they will no longer match the filter."
        }
      },
      vouchers: {
        title: "Voucher Management",
        addBtn: "Add Voucher",
        stats: { total: "Total Vouchers", active: "Active", expired: "Expired", redeemed: "Total Redeemed" },
        filters: { allStatus: "All Status" },
        types: { percent: "Percentage (%)", fixed: "Fixed ($)" },
        statusLabels: { active: "Active", expired: "Expired", exhausted: "Exhausted", inactive: "Disabled", scheduled: "Scheduled" },
        table: { code: "Code", type: "Type", value: "Value", minOrder: "Min Order", limit: "Usage", validity: "Validity" },
        modal: {
          create: "Create Voucher", edit: "Edit Voucher",
          code: "Code", type: "Discount Type", value: "Value",
          max: "Max Discount", min: "Min Order", limit: "Limit",
          from: "From Date", until: "Until Date",
          isActive: "Voucher enabled",
          deleteConfirm: "Permanently delete this voucher?",
          codeHint: "Letters/numbers only — auto-uppercased",
          maxHint: "Cap on % discount (leave blank for none)",
          limitHint: "Max number of redemptions (leave blank for unlimited)"
        }
      },
      reports: {
        title: "Analytics & Reports",
        subtitle: "Insights into bookings, revenue and fleet performance",
        exportBookings: "Export Bookings",
        exportRevenue: "Export Revenue",
        stats: {
          total: "Total Bookings",
          revenue: "Total Revenue",
          completed: "Completed",
          active: "Active",
          users: "Customers",
          cars: "Active Fleet",
          avg: "Avg Booking Value",
          revenuePeriod: "Revenue (range)"
        },
        charts: {
          revenue: "Revenue Chart",
          daily: "Daily", weekly: "Weekly", monthly: "Monthly",
          status: "By Status",
          topCars: "Top Rented Vehicles",
          activity: "Recent Activity",
          noData: "No data in selected range"
        },
        filters: { from: "From", to: "To", reset: "Reset", period: "Period" },
        topCars: { bookings: "Bookings", revenue: "Revenue" },
        activity: { booking: "Booking", transaction: "Transaction", noActivity: "No recent activity" }
      },
      chat: {
        title: "Chat Sessions",
        subtitle: "Customer conversations with the assistant",
        empty: "No chat sessions yet",
        loadError: "Failed to load chat sessions",
        deleteConfirm: "Delete this entire conversation?",
        deleted: "Conversation deleted",
        sessionId: "Session ID",
        guest: "Guest",
        messages: "messages",
        lastActivity: "Last activity",
        startedAt: "Started",
        viewConversation: "View Conversation",
        backToList: "Back to List",
        userLabel: "Customer",
        assistantLabel: "Assistant",
        deleteSession: "Delete Session",
        searchPlaceholder: "Search by customer name or email...",
      }
    }
  },

  vi: {
    nav: {
      home: "Trang chủ", about: "Giới thiệu", services: "Dịch vụ", cars: "Xe",
      blog: "Blog", teams: "Đội ngũ", contact: "Liên hệ",
      login: "Đăng nhập", register: "Đăng ký", profile: "Tài khoản",
      bookingHistory: "Lịch sử đặt xe", cart: "Giỏ hàng", logout: "Đăng xuất",
      admin: "Admin", needHelp: "Cần hỗ trợ?", promotions: "Khuyến mãi",
    },
    auth: {
      loginTitle: "Đăng nhập", loginSub: "Chào mừng trở lại!",
      email: "Email", password: "Mật khẩu", forgotPwd: "Quên mật khẩu?",
      loggingIn: "Đang đăng nhập...", loginBtn: "Đăng nhập",
      noAccount: "Chưa có tài khoản?", registerLink: "Đăng ký",
      registerTitle: "Đăng ký", registerSub: "Tạo tài khoản để đặt xe dễ dàng hơn",
      fullName: "Họ tên", phone: "Số điện thoại",
      confirmPwd: "Xác nhận mật khẩu", registering: "Đang đăng ký...", registerBtn: "Đăng ký",
      hasAccount: "Đã có tài khoản?", loginLink: "Đăng nhập",
      pwdMismatch: "Mật khẩu xác nhận không khớp", pwdTooShort: "Mật khẩu phải ít nhất 6 ký tự",
      registerSuccess: "Đăng ký thành công!",
    },
    cars: {
      transmission: "Hộp số",
      transmission_auto: "Số tự động",
      transmission_manual: "Số sàn",
      fuel: "Nhiên liệu",
      petrol: "Xăng",
      diesel: "Dầu Diesel",
      electric: "Điện",
      hybrid: "Hybrid",
      cng: "Khí nén (CNG)",
      mileage: "Số km",
      seats: "Số chỗ",
      noImage: "Chưa có ảnh",
      statusLabel: { available: "Còn xe", rented: "Đang thuê", maintenance: "Bảo trì" },
      color: "Màu sắc",
      filters: "Bộ lọc",
      priceRange: "Khoảng giá",
      minPrice: "Tối thiểu",
      maxPrice: "Tối đa",
      sortBy: "Sắp xếp",
      sortNewest: "Mới nhất",
      sortPriceAsc: "Giá: Thấp đến cao",
      sortPriceDesc: "Giá: Cao đến thấp",
      sortYearDesc: "Năm: Mới nhất",
      transmissionAuto: "Số tự động",
      transmissionManual: "Số sàn",
      transmissionCVT: "CVT",
      fuelPetrol: "Xăng",
      fuelDiesel: "Diesel",
      fuelElectric: "Điện",
      fuelHybrid: "Hybrid",
      anyTransmission: "Tất cả hộp số",
      anyFuel: "Tất cả nhiên liệu",
      resetFilters: "Xóa bộ lọc",
      activeFilters: "Bộ lọc đang áp dụng",
      foundResults: "kết quả",
      clear: "Xóa",
    },
    carDetails: {
      category: "XE CAO CẤP",
      generalInfo: "Thông tin chung",
      generalDesc: "Trải nghiệm dịch vụ thuê xe cao cấp với điều kiện linh hoạt và dịch vụ hàng đầu.",
      support: "Hỗ trợ 24/7",
      freeCancellation: "Miễn phí hủy & trả xe",
      payOnArrival: "Thanh toán khi nhận xe",
      rentalConditions: "Điều kiện thuê xe",
      conditions: [
        { title: "Hợp đồng và giấy tờ", description: "Cần CMND/CCCD, bằng lái xe và tiền đặt cọc khi ký hợp đồng thuê xe." },
        { title: "Thanh toán", description: "Thanh toán toàn bộ khi thuê, các chi phí phát sinh sẽ được tính thêm." },
        { title: "Giao xe", description: "Miễn phí giao xe trong khu vực, ngoài khu vực sẽ tính phí vận chuyển." },
        { title: "Vi phạm giao thông", description: "Người thuê chịu trách nhiệm với các lỗi vi phạm giao thông." },
      ],
      available: "Còn xe", unavailable: "Không có sẵn",
      rented: "Đang thuê", maintenance: "Bảo trì",
      seatsLabel: "Số chỗ", transmissionLabel: "Hộp số", fuelLabel: "Nhiên liệu",
      mileageLabel: "Số km", acLabel: "Điều hòa", yes: "Có",
      colorLabel: "Màu sắc", descriptionLabel: "Mô tả",
      rentNow: "Thuê ngay", perDay: "/ngày", seatsUnit: "chỗ ngồi",
      selectDates: "Chọn ngày thuê xe",
      pickupDate: "Ngày nhận xe *", returnDate: "Ngày trả xe *",
      total: "Tổng:", days: "ngày",
      addToCart: "Xác nhận đặt xe",
      loginRequired: "Vui lòng đăng nhập để đặt xe",
      selectDatesError: "Vui lòng chọn ngày nhận và trả xe",
      returnAfterPickup: "Ngày trả phải sau ngày nhận",
      addedToCart: "Đã thêm vào giỏ hàng!",
      carNotFound: "Không tìm thấy xe",
    },
    cart: {
      title: "Xác nhận đặt xe",
      empty: "Giỏ hàng trống",
      browseCars: "Xem danh sách xe",
      pickupDate: "Ngày nhận:", returnDate: "Ngày trả:",
      numDays: "Số ngày:", days: "ngày",
      voucherPlaceholder: "Nhập mã giảm giá",
      applyVoucher: "Áp dụng",
      subtotal: "Tạm tính", discount: "Giảm giá", total: "Tổng cộng",
      perDay: "/ngày", confirmBtn: "Xác nhận đặt xe",
      processing: "Đang xử lý...",
      voucherSuccess: "Áp dụng voucher thành công! Giảm",
      invalidVoucher: "Mã không hợp lệ", bookingError: "Không thể tạo đơn đặt xe",
      seats: "chỗ",
      tripDetails: "Thông tin chuyến đi",
      pickupLocation: "Địa điểm nhận xe",
      pickupLocationPlaceholder: "VD: Quận 1, TP.HCM",
      dropoffLocation: "Địa điểm trả xe",
      dropoffLocationPlaceholder: "Cùng nơi nhận hoặc khác",
      notes: "Ghi chú cho nhân viên",
      notesPlaceholder: "Yêu cầu đặc biệt? (không bắt buộc)",
    },
    bookingHistory: {
      title: "Lịch sử đặt xe",
      empty: "Bạn chưa có đơn đặt xe nào",
      status: { pending: "Chờ xác nhận", confirmed: "Đã xác nhận", active: "Đang thuê", completed: "Hoàn tất", cancelled: "Đã hủy" },
      payment: {
        statusLabel: "Thanh toán",
        methodLabel: "Phương thức",
        unpaid: "Chưa thanh toán", paid: "Đã thanh toán", refunded: "Đã hoàn tiền",
        cash: "Tiền mặt", card: "Thẻ tín dụng", mock: "Trực tuyến",
      },
      bookingId: "Mã đơn",
      createdAt: "Ngày đặt",
      discount: "Giảm giá",
      notes: "Ghi chú",
      pickup: "Nhận xe",
      return: "Trả xe",
      duration: "Thời gian thuê",
      payNow: "Thanh toán ngay",
      cancelBtn: "Hủy đặt xe",
      cancelConfirm: "Bạn có chắc muốn hủy đặt xe này?",
      cancelSuccess: "Đã hủy đặt xe",
      cancelError: "Không thể hủy",
      loadError: "Không thể tải lịch sử đặt xe",
    },
    profile: {
      title: "Tài khoản của tôi",
      tabInfo: "Thông tin cá nhân", tabPwd: "Đổi mật khẩu",
      fullName: "Họ tên", phone: "Số điện thoại", address: "Địa chỉ",
      city: "Thành phố", state: "Tỉnh/TP", zipCode: "Mã bưu chính",
      avatar: "URL ảnh đại diện", avatarPlaceholder: "https://example.com/photo.jpg",
      saveBtn: "Lưu thay đổi", saving: "Đang lưu...", saveSuccess: "Cập nhật thành công!",
      currentPwd: "Mật khẩu hiện tại", newPwd: "Mật khẩu mới", confirmPwd: "Xác nhận mật khẩu mới",
      changePwdBtn: "Đổi mật khẩu", changePwdSuccess: "Đổi mật khẩu thành công!",
      pwdMismatch: "Mật khẩu xác nhận không khớp",
    },
    payment: {
      title: "Thanh toán",
      orderSummary: "Tóm tắt đơn hàng",
      car: "Xe", pickupDate: "Ngày nhận", returnDate: "Ngày trả", total: "Tổng",
      paymentMethod: "Phương thức thanh toán",
      creditCard: "Thẻ tín dụng (Mô phỏng)", card: "Thẻ tín dụng thật", cash: "Tiền mặt khi nhận xe",
      payBtn: "Thanh toán", paying: "Đang xử lý...",
      successTitle: "Thanh toán thành công!",
      successDesc: "Đơn đặt xe của bạn đã được xác nhận.",
      viewHistory: "Xem lịch sử đặt xe",
      loadError: "Không tải được thông tin đơn",
      payError: "Thanh toán thất bại",
      paySuccess: "Thanh toán thành công!",
    },
    chatbot: {
      title: "CarShops Assistant",
      subtitle: "Hỗ trợ 24/7",
      placeholder: "Nhập tin nhắn...",
      greeting: "Xin chào! Tôi là trợ lý tư vấn thuê xe. Tôi có thể giúp gì cho bạn?",
      errorReply: "Xin lỗi, tôi không thể trả lời lúc này. Vui lòng thử lại sau.",
    },
    promotions: {
      title: "Khuyến mãi đang diễn ra",
      subtitle: "Áp dụng các mã sau tại trang thanh toán để được giảm giá",
      empty: "Hiện không có khuyến mãi nào đang hoạt động",
      copyCode: "Sao chép mã",
      copied: "Đã sao chép!",
      percentOff: "GIẢM",
      flatOff: "GIẢM",
      minOrder: "Đơn tối thiểu",
      maxDiscount: "Giảm tối đa",
      validUntil: "Hết hạn",
      validFrom: "Bắt đầu",
      usesLeft: "lượt còn lại",
      noLimit: "Không giới hạn",
      apply: "Nhập mã này tại giỏ hàng",
      loadError: "Không thể tải khuyến mãi",
    },
    common: {
      loading: "Đang tải...",
      cancel: "Hủy",
      save: "Lưu",
      delete: "Xóa",
      edit: "Sửa",
      close: "Đóng",
      confirm: "Xác nhận",
    },
    index: {
      heroPremium: "Premium",
      heroTitle: "THUÊ XE",
      heroSubtitle: "THUÊ XE TRỰC TUYẾN NGAY VỚI MỨC GIÁ TỐT NHẤT",
      heroDesc: "Trải nghiệm dịch vụ cho thuê xe cao cấp với sự thoải mái, phong cách và giá cả phải chăng - hoàn hảo cho những chuyến đi đường dài, công tác hoặc những kỳ nghỉ cuối tuần sang trọng.",
      heroViewNow: "Xem Ngay",
      heroRegister: "Đăng ký tại đây",
      selectCarType: "Chọn loại xe khứ hồi",
      pickLocation: "Điểm xuất phát",
      dropLocation: "Địa điểm đến",
      pickDate: "Ngày đi",
      returnDate: "Ngày về",
      aboutSub: "Thuê xe",
      aboutTitle1: "Chúng tôi mang đến nhiều hơn",
      aboutTitle2: "một dịch vụ thuê xe thông thường",
      aboutDesc: "Hệ thống hướng tới cung cấp trải nghiệm đặt xe linh hoạt với khả năng hủy hoặc thay đổi trước thời điểm nhận xe.",
      aboutFeature1: "Xe thể thao và xe hạng sang",
      aboutFeature2: "Nền kinh tế xe hơi",
      aboutReadMore: "Đọc thêm",
      bookBannerSub: "Rent now",
      bookBannerTitle: "Đặt xe tự động",
      luxurySub: "Chọn xe của bạn",
      luxuryTitle1: "Danh sách",
      luxuryTitle2: "Xe Có Thể Chọn",
      carDescBtn: "Mô tả",
      carTypeSub: "Chọn xe của bạn",
      carTypeTitle1: "Danh Sách",
      carTypeTitle2: "Xe Có Thể Chọn",
      carTypeConvertible: "Xe Mui Trần",
      carTypeSport: "Xe Thể Thao",
      carTypeLuxury: "Xe Hạng Sang",
      carTypeSmall: "Xe Cỡ Nhỏ",
      serviceSub: "Chúng Tôi Làm Gì",
      serviceTitle: "Để Phục Vụ Khách Hàng",
      service1Title: "Thuê Xe Theo Ngày",
      service1Desc: "Cho thuê xe theo ngày cho phép khách hàng lựa chọn phương tiện và thời gian thuê cụ thể theo ngày, phù hợp với nhu cầu di chuyển ngắn hạn.",
      service2Title: "Thuê Xe Theo Tháng",
      service2Desc: "Dịch vụ thuê xe với thời gian trên 1 tháng được chúng tôi xếp vào nhóm dịch vụ cho thuê xe dài hạn. Đây là dịch vụ chủ lực của chúng tôi, được cung cấp cho cả khách hàng cá nhân và khách hàng doanh nghiệp.",
      service3Title: "Cho Thuê Xe Cưới",
      service3Desc: "Xe cưới cũng là yếu tố quan trọng giúp đám cưới của bạn thêm phần hoàn hảo hơn. Là phương tiện cực kì quan trọng trong ngày cưới(Công ty chúng tôi không nhận trang trí xe cưới).",
      testSub: "Đánh Giá (Demo)",
      testTitle1: "Khách Hàng Nói Gì Về Chúng Tôi",
      testTitle2: "(Dữ Liệu Mẫu)",
      testRole: "Khách Hàng",
      testReview1: "Thật là tuyệt vời",
      testReview2: "Sẽ quay lại lần 2!",
      testReview3: "Lân đầu tôi thấy gara nào cho thuê xe sang mà rẻ như này!!!",
      testReview4: "I am a foreigner residing in Vietnam. I find the service here to be excellent.",
      testReview5: "Nội thất xe sạch sẽ, trước khi đến còn gọi báo trước 25 phút.",
      blogSub: "Bài Báo Về Chúng Tôi",
      blogTitle1: "Bảng Tin",
      blogTitle2: "Cần Thiết",
      blogCategory: "Xe hơi",
      blogPost1: "Giấy tờ cần thiết cho thuê xe",
      blogPost2: "Chi phí thuê xe thể thao và các loại xe khác.",
      blogPost3: "Thuê xe ô tô: Làm thế nào để kiểm tra các khoản phạt khi lái xe?",
      blogPost4: "Làm thế nào để thuê xe tại nhà ga sân bay?",
    },
    about: {
      bannerSub: "- Thông Tin",
      bannerTitle1: "Về",
      bannerTitle2: "Chúng Tôi",
      heading1: "Chúng tôi mang đến nhiều hơn",
      heading2: "một dịch vụ thuê xe thông thường",
      desc: "Hầu hết các đặt phòng cho thuê đều cho phép hủy hoặc thay đổi miễn phí.",
      sedan: "4 chỗ (Sedan)",
      suv: "Xe gầm cao (SUV)",
      luxury: "Cao cấp (Luxury)",
      sports: "Xe thể thao (Sports)",
      coupe: "Xe 2 cửa (Coupe)",
      hatchback: "Xe đô thị (Hatchback)",
      pickLocation: "Địa Điểm Xuất Phát",
      dropLocation: "Địa Điểm Đến",
      pickDate: "Ngày Rời Đi",
      returnDate: "Ngày Trở Về",
      bookBtn: "Đặt Xe",
    },
    services: {
      bannerSub: "- Chúng Tôi Làm Gì",
      bannerTitle1: "Để",
      bannerTitle2: "Phục Vụ Bạn",
      servicesSub: "Chúng Tôi Làm Gì",
      servicesTitle: "Để Phục Vụ Khách Hàng",
      card1Title: "Dịch vụ thuê xe doanh nghiệp",
      card1Desc: "Thuê xe doanh nghiệp hỗ trợ các tổ chức, công ty thuê phương tiện theo nhu cầu sử dụng dài hạn hoặc theo hợp đồng, giúp tối ưu chi phí và quản lý hiệu quả.",
      card2Title: "Dịch Vụ Thuê Xe Có Tài Xế",
      card2Desc: "Thuê xe có tài xế cho phép khách hàng lựa chọn phương tiện kèm theo tài xế, phù hợp với nhu cầu di chuyển an toàn, tiện lợi và không cần tự lái.",
      card3Title: "Dịch Vụ Đưa Đón Tại Sân Bay",
      card3Desc: "Đưa đón sân bay cho phép khách hàng đặt xe di chuyển giữa sân bay và các địa điểm theo yêu cầu, đảm bảo đúng giờ, thuận tiện và an toàn.",
      card4Title: "Đặt Thuê Nhiều Xe Cùng Lúc",
      card4Desc: "Cho phép khách hàng (cá nhân hoặc doanh nghiệp) đặt nhiều phương tiện cùng lúc, đáp ứng nhu cầu tổ chức sự kiện, du lịch hoặc vận chuyển quy mô lớn.",
      card5Title: "Dành Cho Khách VIP (comming soon!)",
      card5Desc: "Chức năng dành cho khách VIP cung cấp các dịch vụ cao cấp với ưu đãi đặc biệt, hỗ trợ riêng và trải nghiệm tốt hơn cho người dùng có nhu cầu cao.",
      card6Title: "Cho Thuê Xe Doanh Nghiệp",
      card6Desc: "Dịch vụ cho thuê xe doanh nghiệp hỗ trợ các tổ chức, công ty thuê phương tiện theo nhu cầu dài hạn hoặc theo hợp đồng, giúp tối ưu chi phí và nâng cao hiệu quả quản lý.",
      dailyTitle: "Thuê Xe Theo Ngày",
      dailyDesc: "Cho thuê xe theo ngày cho phép khách hàng lựa chọn phương tiện và thời gian thuê cụ thể theo ngày, phù hợp với nhu cầu di chuyển ngắn hạn.",
      monthlyTitle: "Thuê Xe Theo Tháng",
      monthlyDesc: "Dịch vụ thuê xe với thời gian trên 1 tháng được chúng tôi xếp vào nhóm dịch vụ cho thuê xe dài hạn. Đây là dịch vụ chủ lực của chúng tôi, được cung cấp cho cả khách hàng cá nhân và khách hàng doanh nghiệp.",
      weddingTitle: "Cho Thuê Xe Cưới",
      weddingDesc: "Xe cưới cũng là yếu tố quan trọng giúp đám cưới của bạn thêm phần hoàn hảo hơn. Là phương tiện cực kì quan trọng trong ngày cưới(Công ty chúng tôi không nhận trang trí xe cưới).",
    },
    contact: {
      bannerSub: "Liên Hệ Ngay",
      bannerTitle1: "Với",
      bannerTitle2: "Chúng Tôi",
      addressLabel: "Địa chỉ",
      hoursLabel: "Giờ làm việc",
      hoursValue: "Thứ 2 - Chủ nhật: 8:00 - 19:00",
      phoneLabel: "Điện thoại",
      formTitle: "Gửi thông tin liên hệ",
      namePlaceholder: "Họ và tên*",
      phonePlaceholder: "Số điện thoại*",
      subjectPlaceholder: "Tiêu đề*",
      messagePlaceholder: "Nội dung*",
      sendBtn: "Gửi liên hệ",
    },
    teams: {
      bannerSub: "TƯ VẤN VIÊN",
      bannerTitle: "Olivia Brown (Dữ Liệu Mẫu)",
      greeting: "Xin chào, tôi là Olivia Brown – chuyên viên tư vấn tại hệ thống thuê xe cao cấp.",
      memberDesc: "Hỗ trợ khách hàng lựa chọn xe phù hợp, tư vấn dịch vụ và đảm bảo trải nghiệm thuê xe thuận tiện, nhanh chóng.",
      license: "Bằng lái xe hạng B",
      education: "Tốt nghiệp đại học",
      communication: "Kỹ năng giao tiếp tốt",
      tab1: "Tiểu sử",
      tab2: "Học vấn",
      tab3: "Thành tựu",
      bio: "Chuyên viên tư vấn dịch vụ thuê xe với kinh nghiệm trong lĩnh vực chăm sóc khách hàng và hỗ trợ lựa chọn phương tiện phù hợp. Có khả năng tư vấn nhanh chóng, chính xác và mang lại trải nghiệm tốt nhất cho khách hàng.",
      edu: "Tốt nghiệp chuyên ngành Công nghệ thông tin / Quản trị kinh doanh. Được đào tạo về kỹ năng giao tiếp, quản lý dịch vụ và vận hành hệ thống hỗ trợ khách hàng trong môi trường số.",
      achievement: "Đạt danh hiệu nhân viên xuất sắc trong quá trình làm việc, có nhiều đóng góp trong việc nâng cao chất lượng dịch vụ và cải thiện trải nghiệm người dùng trên hệ thống thuê xe trực tuyến.",
      teamSub: "- Đội ngũ chuyên nghiệp",
      teamTitle1: "Đội ngũ",
      teamTitle2: "Chuyên gia",
      dept: "Phòng kinh doanh",
    },
    footer: {
      quickRentSub: "Thuê Xe Nhanh",
      quickRentTitle: "Mà Không Cần Đặt Trước?",
      quickRentDesc: "Đừng Ngần Ngại Mà Hãy Nhắn Tin Cho Chúng Tôi",
      callLabel: "Gọi cho tôi tại",
      emailLabel: "Phản hổi cho chúng tôi",
      addressLabel: "Địa Chỉ Đặt Xe",
      tagline: "Trải nghiệm sự dễ dàng và tiện lợi khi thuê xe với Carshops.",
      quickLinks: "Truy cập nhanh",
      subscribe: "Subscribe",
      subscribeDesc: "Hãy theo dõi chúng tôi để nhận được những ưu đãi mới nhất.",
      emailPlaceholder: "Your email address",
      copyright: "Mọi quyền được bảo lưu.",
    },
    admin: {
      sidebar: {
        addCar: "Thêm xe mới",
        manageCars: "Quản lý đội xe",
        bookings: "Đơn đặt xe",
        users: "Người dùng",
        categories: "Danh mục",
        vouchers: "Khuyến mãi",
        financial: "Tài chính",
        reports: "Báo cáo",
        chat: "Phiên chat",
        logout: "Đăng xuất"
      },
      common: {
        welcome: "Chào mừng trở lại",
        dashboard: "Bảng điều khiển Admin",
        search: "Tìm kiếm dữ liệu...",
        actions: "Thao tác",
        status: "Trạng thái",
        save: "Lưu thay đổi",
        discard: "Hủy bỏ",
        loading: "Đang tải dữ liệu...",
        noResults: "Không tìm thấy kết quả",
        error: "Lỗi",
        saveSuccess: "Lưu thành công",
        loadingError: "Không tải được dữ liệu",
        confirmDelete: "Hành động này không thể hoàn tác. Tiếp tục?",
        add: "Thêm mới", edit: "Sửa", cancel: "Hủy", create: "Tạo", delete: "Xóa",
        active: "Hoạt động", inactive: "Tạm khóa"
      },
      pagination: {
        showing: "Hiển thị",
        to: "đến",
        of: "trên",
        results: "kết quả",
        prev: "Trước",
        next: "Sau",
        rowsPerPage: "Số dòng/trang"
      },
      cars: {
        title: "Danh sách đội xe",
        stats: {
          total: "Tổng đội xe", unit: "phương tiện",
          available: "Sẵn sàng", rented: "Đang thuê", maintenance: "Bảo trì"
        },
        filters: { allStatus: "Tất cả trạng thái" },
        table: { identity: "Thông tin xe", specs: "Thông số kỹ thuật", rate: "Giá thuê/Ngày" },
        modal: {
          title: "Cập nhật phương tiện",
          make: "Hãng xe", model: "Dòng xe", year: "Năm sản xuất",
          rate: "Giá thuê ($)", trans: "Hộp số", fuel: "Nhiên liệu",
          seats: "Số ghế", mileage: "Mức tiêu thụ (MPG)", color: "Màu sắc",
          category: "Phân khúc", description: "Mô tả",
          image: "Hình ảnh xe", currentImage: "Ảnh hiện tại",
          uploadNew: "Tải ảnh mới", keepCurrent: "Giữ ảnh hiện tại",
          deleteConfirm: "Bạn có chắc chắn muốn xóa xe này?"
        }
      },
      bookings: {
        title: "Quản lý đơn thuê",
        stats: {
          total: "Tổng đơn",
          active: "Đang thuê", revenue: "Doanh thu (đã thanh toán)", pending: "Chờ duyệt",
          confirmed: "Đã xác nhận", completed: "Hoàn tất", cancelled: "Đã hủy"
        },
        filters: { allStatus: "Tất cả trạng thái", allPayment: "Tất cả thanh toán" },
        payment: {
          status: "Tình trạng thanh toán",
          method: "Phương thức",
          unpaid: "Chưa thanh toán", paid: "Đã thanh toán", refunded: "Đã hoàn tiền",
          cash: "Tiền mặt", card: "Thẻ", mock: "Thử nghiệm"
        },
        table: { customer: "Khách hàng", car: "Phương tiện", duration: "Thời gian", amount: "Tổng tiền" },
        modal: {
          title: "Chi tiết đơn đặt xe",
          summary: "Tóm tắt đơn hàng", financials: "Tài chính",
          days: "Số ngày thuê", payment: "Hình thức trả",
          bookingId: "Mã đơn", createdAt: "Ngày tạo", notes: "Ghi chú",
          discount: "Giảm giá", subtotal: "Tạm tính",
          updateStatus: "Cập nhật trạng thái", cancelBooking: "Hủy đơn",
          cancelConfirm: "Bạn có chắc chắn muốn hủy đơn đặt xe này?"
        }
      },
      users: {
        title: "Danh bạ người dùng",
        stats: {
          total: "Tổng người dùng", privilege: "Quản trị viên",
          acquisition: "Mới (7 ngày)", customers: "Khách hàng"
        },
        filters: { allRoles: "Tất cả vai trò", admin: "Quản trị", customer: "Khách hàng" },
        table: { identity: "Định danh", contact: "Thông tin liên hệ", role: "Quyền hạn", joined: "Ngày gia nhập" },
        roles: { admin: "Quản trị", customer: "Khách hàng" },
        modal: {
          addTitle: "Thêm người dùng",
          editTitle: "Sửa người dùng",
          name: "Họ và tên", email: "Email", password: "Mật khẩu",
          phone: "Số điện thoại", role: "Vai trò", status: "Trạng thái tài khoản",
          passwordHint: "Tối thiểu 6 ký tự",
          deleteConfirm: "Xóa vĩnh viễn người dùng này?",
          activate: "Kích hoạt", suspend: "Khóa",
          selfTag: "Bạn",
          selfActionDisabled: "Không thể tự thay đổi vai trò hoặc trạng thái của chính mình"
        }
      },
      addCar: {
        title: "Đăng ký",
        titleHighlight: "Xe mới",
        subtitle: "Điền thông tin chi tiết bên dưới để thêm xe vào đội xe cho thuê của chúng tôi",
        labels: {
          name: "Tên xe",
          price: "Giá thuê ngày ($)",
          seats: "Số ghế",
          fuel: "Loại nhiên liệu",
          mileage: "Mức tiêu thụ (MPG)",
          category: "Phân khúc",
          year: "Năm sản xuất",
          model: "Phiên bản",
          transmission: "Hộp số",
          color: "Màu sắc",
          description: "Mô tả",
          image: "Hình ảnh xe"
        },
        placeholders: {
          name: "vd: Toyota Camry",
          price: "45",
          mileage: "28",
          year: "2020",
          model: "vd: XLE",
          description: "Mô tả chi tiết về xe...",
          upload: "Nhấp để tải lên",
          drop: "hoặc kéo thả vào đây",
          imageTypes: "Hỗ trợ PNG, JPG, WEBP tối đa 10MB"
        },
        success: {
          title: "Chúc mừng!",
          message: "đã được đăng ký thành công"
        },
        submit: "Thêm xe",
        sections: {
          info: "Thông tin cơ bản",
          specs: "Thông số kỹ thuật",
          media: "Mô tả & Hình ảnh",
          preview: "Xem trước giao diện"
        }
      },
      financial: {
        title: "Tổng quan Tài chính",
        subtitle: "Lịch sử giao dịch và thống kê doanh thu",
        stats: {
          revenue: "Tổng doanh thu",
          revenueSub: "Từ các giao dịch thành công",
          transactions: "Tổng giao dịch",
          transactionsSub: "Tất cả các trạng thái",
          growth: "Tỉ lệ thành công",
          growthSub: "giao dịch",
          pending: "Doanh thu chờ",
          pendingSub: "Đang chờ xác nhận",
          refunded: "Đã hoàn tiền",
          refundedSub: "Trả lại cho khách",
          avg: "Trung bình",
          avgSub: "Mỗi giao dịch thành công"
        },
        filters: { allStatus: "Tất cả trạng thái", allMethods: "Tất cả phương thức", from: "Từ ngày", to: "Đến ngày", reset: "Đặt lại" },
        methods: { cash: "Tiền mặt", card: "Thẻ", mock: "Thử nghiệm" },
        table: {
          id: "Mã GD",
          customer: "Khách hàng",
          method: "PTTT",
          amount: "Số tiền",
          status: "Trạng thái",
          date: "Ngày"
        },
        status: {
          success: "Thành công",
          pending: "Chờ xử lý",
          failed: "Thất bại",
          refunded: "Hoàn tiền",
          all: "Tất cả trạng thái"
        },
        modal: {
          title: "Chi tiết giao dịch",
          gatewayRef: "Mã cổng thanh toán",
          description: "Mô tả",
          customer: "Khách hàng",
          bookingId: "Mã đơn",
          createdAt: "Tạo lúc",
          updatedAt: "Cập nhật lúc",
          changeStatus: "Đổi trạng thái",
          refund: "Hoàn tiền",
          markPaid: "Đánh dấu đã trả",
          refundConfirm: "Đánh dấu giao dịch này là đã hoàn tiền? Trạng thái thanh toán của đơn sẽ chuyển sang 'refunded'."
        },
        export: "Xuất Excel"
      },
      categories: {
        title: "Quản lý Danh mục",
        addBtn: "Thêm danh mục",
        stats: { total: "Tổng danh mục", active: "Đang hoạt động", hidden: "Đã ẩn", carsTagged: "Xe được gắn" },
        table: { name: "Tên", count: "Số xe", status: "Trạng thái" },
        modal: {
          create: "Thêm danh mục", edit: "Sửa danh mục",
          name: "Tên danh mục", icon: "Biểu tượng (Emoji)", desc: "Mô tả",
          deleteConfirm: "Ẩn danh mục này?",
          deleteWithCarsWarning: "Danh mục này đang gắn với {n} xe. Việc ẩn sẽ không xóa xe nhưng các xe sẽ không khớp bộ lọc nữa."
        }
      },
      vouchers: {
        title: "Quản lý Khuyến mãi",
        addBtn: "Thêm voucher",
        stats: { total: "Tổng voucher", active: "Đang hoạt động", expired: "Hết hạn", redeemed: "Lượt đã dùng" },
        filters: { allStatus: "Tất cả trạng thái" },
        types: { percent: "Phần trăm (%)", fixed: "Cố định ($)" },
        statusLabels: { active: "Hoạt động", expired: "Hết hạn", exhausted: "Hết lượt", inactive: "Đã tắt", scheduled: "Chờ kích hoạt" },
        table: { code: "Mã", type: "Loại", value: "Giá trị", minOrder: "Đơn tối thiểu", limit: "Lượt dùng", validity: "Hiệu lực" },
        modal: {
          create: "Tạo voucher", edit: "Sửa voucher",
          code: "Mã code", type: "Loại giảm giá", value: "Giá trị",
          max: "Giảm tối đa", min: "Đơn tối thiểu", limit: "Giới hạn",
          from: "Từ ngày", until: "Đến ngày",
          isActive: "Bật voucher",
          deleteConfirm: "Xóa vĩnh viễn voucher này?",
          codeHint: "Chỉ chữ/số — sẽ tự động viết hoa",
          maxHint: "Số tiền giảm tối đa (để trống = không giới hạn)",
          limitHint: "Số lượt dùng tối đa (để trống = không giới hạn)"
        }
      },
      reports: {
        title: "Báo cáo & Thống kê",
        subtitle: "Phân tích đơn đặt, doanh thu và hiệu suất đội xe",
        exportBookings: "Xuất đơn đặt",
        exportRevenue: "Xuất doanh thu",
        stats: {
          total: "Tổng đơn",
          revenue: "Tổng doanh thu",
          completed: "Hoàn tất",
          active: "Đang thuê",
          users: "Khách hàng",
          cars: "Xe đang phục vụ",
          avg: "Giá trị TB/đơn",
          revenuePeriod: "Doanh thu (khoảng đã chọn)"
        },
        charts: {
          revenue: "Biểu đồ doanh thu",
          daily: "Ngày", weekly: "Tuần", monthly: "Tháng",
          status: "Theo trạng thái",
          topCars: "Top xe được thuê",
          activity: "Hoạt động gần đây",
          noData: "Không có dữ liệu trong khoảng đã chọn"
        },
        filters: { from: "Từ ngày", to: "Đến ngày", reset: "Đặt lại", period: "Chu kỳ" },
        topCars: { bookings: "Lượt thuê", revenue: "Doanh thu" },
        activity: { booking: "Đơn đặt", transaction: "Giao dịch", noActivity: "Chưa có hoạt động" }
      },
      chat: {
        title: "Phiên chat",
        subtitle: "Hội thoại của khách hàng với trợ lý",
        empty: "Chưa có phiên chat nào",
        loadError: "Không tải được danh sách chat",
        deleteConfirm: "Xóa toàn bộ cuộc hội thoại này?",
        deleted: "Đã xóa cuộc hội thoại",
        sessionId: "Mã phiên",
        guest: "Khách",
        messages: "tin nhắn",
        lastActivity: "Hoạt động cuối",
        startedAt: "Bắt đầu",
        viewConversation: "Xem hội thoại",
        backToList: "Quay lại danh sách",
        userLabel: "Khách hàng",
        assistantLabel: "Trợ lý",
        deleteSession: "Xóa phiên",
        searchPlaceholder: "Tìm theo tên hoặc email khách hàng...",
      }
    }
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "vi");

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem("lang", l);
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
